import {log} from '../utils'
import {logCombat} from '../combatlog'
import {AudioPlayer} from './audio'
import type {GameLoop} from './game-loop'
import {GlobalCooldown} from './global-cooldown'
import type {Character} from './character'
import type {Spell} from './spell'
// Type-only: a value import here would close the loop `actions → balance → spells → spell-cast`
// and leave the balance snapshot reading half-built spell classes.
import type {ActionResult} from '../actions'

type SpellClass = typeof Spell

type CastFailure =
	| 'dead'
	| 'global-cooldown'
	| 'already-casting'
	| 'missing-target'
	| 'missing-spell'
	| 'missing-mana'
	| 'cooldown'

const failureMessage: Record<CastFailure, string> = {
	dead: `Can't cast while dead`,
	'global-cooldown': `Can't cast during global cooldown`,
	'already-casting': `Can't cast while casting`,
	'missing-target': `Can't cast without a target`,
	'missing-spell': `Spell not found in spellbook`,
	'missing-mana': 'Not enough mana',
	cooldown: 'Still on cooldown',
}

export class SpellCast {
	/** Refusals come back as `{ok: false, error}` rather than a warning nobody reads. */
	static cast(caster: Character, spellName: string): ActionResult<Spell> {
		log(`cast:${spellName}`)

		const SpellClass = caster.spellbook[spellName]
		const failure = this.validate(caster, SpellClass)
		if (failure) {
			const error = failure === 'missing-spell' ? `Spell ${spellName} not found in spellbook` : failureMessage[failure]
			return {ok: false, error}
		}

		const spell = new SpellClass(caster)
		caster.spell = spell
		caster.lastCastTime = (caster.root as GameLoop).elapsedTime
		return {ok: true, value: spell}
	}

	/** The two halves below, in the order they always refused in. */
	static validate(caster: Character, SpellClass?: SpellClass): CastFailure | undefined {
		return this.whyNotAct(caster) ?? this.whyNotCast(caster, SpellClass)
	}

	/**
	 * What stops this caster acting at all, whatever they meant to cast. True of the player's whole
	 * action bar at once, and it flickers — the global cooldown is up for a moment after every cast.
	 */
	static whyNotAct(caster: Character): CastFailure | undefined {
		if (caster.health.current <= 0) return 'dead'
		if (caster.gcd) return 'global-cooldown'
		if (caster.spell) return 'already-casting'
		return undefined
	}

	/**
	 * What stops this spell landing on this target. `target` is the cast being *considered*, not
	 * always the one the caster has selected — the Autopilot picks who to heal and hands the target
	 * over with the cast, and `getTarget()` would answer about a different cast than it meant.
	 */
	static whyNotCast(caster: Character, SpellClass?: SpellClass, target = caster.getTarget()): CastFailure | undefined {
		// `alive` and not just presence: the default `getTarget()` already filters corpses, so
		// only an explicitly passed target could be a dead one, and healing a corpse is not a cast.
		if (!target?.alive) return 'missing-target'
		if (!SpellClass) return 'missing-spell'
		// Before mana, because a cooldown is the constraint you can do nothing about — mana may
		// well have regenerated by the time the spell is available again.
		if (this.cooldownRemaining(caster, SpellClass) > 0) return 'cooldown'
		if (SpellClass.cost && caster.mana && caster.mana.current < SpellClass.cost) return 'missing-mana'
		return undefined
	}

	/** How much longer this spell is on its own cooldown, in ms. Zero when it is ready. */
	static cooldownRemaining(caster: Character, SpellClass: SpellClass): number {
		const until = caster.cooldowns.get(SpellClass.name)
		if (until === undefined) return 0
		return Math.max(0, until - (caster.root as GameLoop).elapsedTime)
	}

	static mount(spell: Spell) {
		const caster = spell.parent

		caster.gcd = new GlobalCooldown(caster)

		logCombat({
			timestamp: Date.now(),
			eventType: 'SPELL_CAST_START',
			sourceId: caster.id,
			sourceName: caster.name,
			spellId: spell.name,
			spellName: spell.name,
			value: spell.delay,
			// An instant cast still costs the global cooldown, so the longer of the two is what the
			// caster actually loses. This is where "the healer is never busier than 40%" comes from.
			busyFor: Math.max(spell.delay, caster.gcd.delay),
		})

		if (spell.delay) {
			AudioPlayer.play('spell_precast', {loop: true, owner: spell})
		}
	}

	static succeed(spell: Spell) {
		const caster = spell.parent

		logCombat({
			timestamp: Date.now(),
			eventType: 'SPELL_CAST_SUCCESS',
			sourceId: caster.id,
			sourceName: caster.name,
			spellId: spell.name,
			spellName: spell.name,
		})
	}

	static finish(spell: Spell) {
		const caster = spell.parent
		const gameLoop = spell.root as GameLoop
		const completed = spell._cycles > 0

		AudioPlayer.stopOwned(spell)

		caster.spell = undefined

		if (completed) {
			caster.lastCastCompletedTime = gameLoop.elapsedTime
			// Starts when the cast lands, not when it began, so a long cast is not partly free.
			if (spell.cooldown) caster.cooldowns.set(spell.name, gameLoop.elapsedTime + spell.cooldown)
		} else {
			logCombat({
				timestamp: Date.now(),
				eventType: 'SPELL_CAST_INTERRUPTED',
				sourceId: caster.id,
				sourceName: caster.name,
				spellId: spell.name,
				spellName: spell.name,
			})
		}

		// Instant casts let their GCD task expire naturally; interrupted cast-time spells clear it.
		if (spell.delay > 0) {
			caster.gcd = undefined
		}

		if (completed && caster.mana) {
			caster.mana.spend(spell.cost)
			logCombat({
				timestamp: Date.now(),
				eventType: 'RESOURCE_SPENT',
				sourceId: caster.id,
				sourceName: caster.name,
				value: -spell.cost,
				extraInfo: 'MANA',
			})
		}
	}
}
